# Default values for bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: "ghcr.io"
  repository: ZadorozhnaI/kbot
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.3-a560eee-linux-amd64"
  os: linux
  arch: amd64

  secret:
    name: kbot
    tokenKey: token
    tokenName: TELE_TOKEN
