replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "zadorozhnai/kbot"
  tag: "v1.1.3-820cfcd"
  os: linux
  arch: amd64
  secret:
    name: kbot
    tokenKey: token
    tokenName: TELE_TOKEN
  securityContext:
    privileged: true
